import React from 'react';
import "./header.css";
import people from "../../assets/assets/people.png";
import ai from "../../assets/assets/ai.png"

const Header = () => {
  return (
    <div className="gpt3__header" id="home">

      <div className="gpt3__header-content_container">
        <h1 className='gradient__text'>
          Let's Build Something amazing with GPT-3 OpenAI
        </h1>
        <p>The arrival of the web-based software GPT-3 as an API service for developers has started to impact the higher education landscape.The quality of the text generated by GPT-3 is so high that it can be difficult to determine whether or not it was written by a human, which has both benefits and risks.</p>
        <div className="gpt3__header-content-input">
          <input type="email" placeholder="Your Email Address"/>
          <button type="button">Get Started</button>
        </div>
        <div className="gpt3__header-content-people">
          <img src={people} alt="people"/>
          <p>1600 people requested access in 16 hours.</p>
        </div>
      </div>

      <div className="gpt3__header-image_container">
        <img src={ai} alt="ai"/>
      </div>

    </div>
  )
}

export default Header
